spring:
  application:
    name: usage-management-api
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        prefetch: 1  # 순서 보장을 위해 prefetch 값을 1로 설정
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: false
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2.0
  datasource:
    url: ${DB_URL:jdbc:postgresql://20.249.197.182:5432/telecomdb}
    username: ${DB_USERNAME:telecomuser}
    password: ${DB_PASSWORD:P@ssw0rd}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /    # 컨텍스트 패스 설정
  port: 8080


logging:
  level:
    com.telco.management.api: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      app: usage-management-api
      instance: ${HOSTNAME:localhost}:${server.port:8080}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms

app:
  queue:
    partitions: 8