FROM openjdk:17-slim
WORKDIR /app
COPY query-service/usage-query-service.jar app.jar
#ENTRYPOINT ["java","-jar","app.jar"]
ENV JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseG1GC"
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
