# Usage Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-management
  labels: # 추가
    app: usage-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage-management
  template:
    metadata:
      labels:
        app: usage-management
    spec:
      containers:
        - name: usage-management
#          image: ${REGISTRY}/telecom/usage-management:${IMAGE_TAG}
          image: usageqcr.azurecr.io/telecom/usage-management:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m -XX:+UseG1GC"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: usage-management
spec:
  selector:
    app: usage-management
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usage-management-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usage-management
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# Usage Query Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-query
  labels: # 추가
    app: usage-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage-query
  template:
    metadata:
      labels:
        app: usage-query
    spec:
      containers:
        - name: usage-query
#          image: ${REGISTRY}/telecom/usage-query:${IMAGE_TAG}
          image: usageqcr.azurecr.io/telecom/usage-query:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m -XX:+UseG1GC"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: usage-query
spec:
  selector:
    app: usage-query
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usage-query-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usage-query
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80