# Usage Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-management
  labels: # 추가
    app: usage-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage-management
  template:
    metadata:
      labels:
        app: usage-management
    spec:
      containers:
        - name: usage-management
          image: usageqcr.azurecr.io/telecom/usage-management:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone-config
          volumes:
            - hostPath:
                path: /usr/share/zoneinfo/Asia/Seoul
              name: timezone-config
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: usage-management
spec:
  selector:
    app: usage-management
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usage-management-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usage-management
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# Usage Query Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-query
  labels: # 추가
    app: usage-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage-query
  template:
    metadata:
      labels:
        app: usage-query
    spec:
      containers:
        - name: usage-query
          image: usageqcr.azurecr.io/telecom/usage-query:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone-config
          volumes:
            - hostPath:
                path: /usr/share/zoneinfo/Asia/Seoul
              name: timezone-config
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: usage-query
spec:
  selector:
    app: usage-query
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usage-query-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usage-query
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80