spring:
  app:
    query:
      delay-millis: 0  # 기본 딜레이 값 (밀리초)
  data:
    redis:
      host: ${REDIS_HOST:20.249.206.186}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:Passw0rd}
      ttl: ${REDIS_TTL:600}
      timeout: 3000 # 연결 타임아웃: 3초
      lettuce: # Redis 클라이언트로 Lettuce 사용
        pool:
          max-active: 8  # 최대 연결 수
          max-idle: 8    # 최대 유휴 연결 수
          min-idle: 0    # 최소 유휴 연결 수
          max-wait: 1000 # 최대 대기 시간
  datasource:
    url: ${DB_URL:jdbc:postgresql://20.249.197.182:5432/telecomdb}
    username: ${DB_USERNAME:telecomuser}
    password: ${DB_PASSWORD:P@ssw0rd}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# monitor
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      app: usage-query-service
      instance: ${HOSTNAME:localhost}:${server.port:8080}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        cache.operation: true
      slo:
        http.server.requests: 100ms, 500ms, 1s
        cache.operation: 50ms, 100ms, 200ms