spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:20.249.199.104}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:P@ssw0rd$}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2.0
  datasource:
    url: ${DB_URL:jdbc:postgresql://20.249.197.182:5432/telecomdb}
    username: ${DB_USERNAME:telecomuser}
    password: ${DB_PASSWORD:P@ssw0rd}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Common Module Source Files
