spring:
  data:
    redis:
      host: ${REDIS_HOST:20.249.198.38}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:P@ssw0rd}
      ttl: ${REDIS_TTL:600}
      timeout: 3000 # 연결 타임아웃: 3초
      lettuce: # Redis 클라이언트로 Lettuce 사용
        pool:
          max-active: 8  # 최대 연결 수
          max-idle: 8    # 최대 유휴 연결 수
          min-idle: 0    # 최소 유휴 연결 수
          max-wait: 1000 # 최대 대기 시간
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq} # 20.249.199.104
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:P@ssw0rd$}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2.0
  datasource:
    url: ${DB_URL:jdbc:postgresql://20.249.197.182:5432/telecomdb}
    username: ${DB_USERNAME:telecomuser}
    password: ${DB_PASSWORD:P@ssw0rd}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Common Module Source Files

# health check
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true  # K8s liveness/readiness probe 지원