name: Usage Services CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  NAMESPACE: usageq-ns

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew :usage-management-service:clean :usage-management-service:build
          ./gradlew :usage-query-service:clean :usage-query-service:build

      - name: Upload query service artifact
        uses: actions/upload-artifact@v3
        with:
          name: query-service
          path: usage-query-service/build/libs/*.jar

      - name: Upload management service artifact
        uses: actions/upload-artifact@v3
        with:
          name: management-service
          path: usage-management-service/build/libs/*.jar

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate image tag
        id: generate_tag
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Download query service artifact
        uses: actions/download-artifact@v3
        with:
          name: query-service
          path: query-service

      - name: Download management service artifact
        uses: actions/download-artifact@v3
        with:
          name: management-service
          path: management-service

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push query service image
        run: |
          docker build -t ${{ env.REGISTRY }}/telecom/usage-query:${{ steps.generate_tag.outputs.tag }} \
            -f deployment/Dockerfile-usage-query .
          docker tag ${{ env.REGISTRY }}/telecom/usage-query:${{ steps.generate_tag.outputs.tag }} \
            ${{ env.REGISTRY }}/telecom/usage-query:latest
          docker push ${{ env.REGISTRY }}/telecom/usage-query:${{ steps.generate_tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/telecom/usage-query:latest

      - name: Build and push management service image
        run: |
          docker build -t ${{ env.REGISTRY }}/telecom/usage-management:${{ steps.generate_tag.outputs.tag }} \
            -f deployment/Dockerfile-usage-management .
          docker tag ${{ env.REGISTRY }}/telecom/usage-management:${{ steps.generate_tag.outputs.tag }} \
            ${{ env.REGISTRY }}/telecom/usage-management:latest
          docker push ${{ env.REGISTRY }}/telecom/usage-management:${{ steps.generate_tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/telecom/usage-management:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'prod' }}
    env:
      IMAGE_TAG: ${{ needs.docker-build.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Create namespace if not exists
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Create ConfigMap and Secrets
        run: |
          # Create ConfigMap
          kubectl create configmap app-config \
            --namespace ${{ env.NAMESPACE }} \
            --from-literal=SPRING_PROFILES_ACTIVE=${{ github.event.inputs.environment || 'prod' }} \
            --from-literal=SERVER_PORT=8080 \
            --dry-run=client -o yaml | kubectl apply -f -

          # Create Secrets
          kubectl create secret generic app-secret \
            --namespace ${{ env.NAMESPACE }} \
            --from-literal=DB_URL=${{ secrets.DB_URL }} \
            --from-literal=DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --from-literal=DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --from-literal=REDIS_HOST=${{ secrets.REDIS_HOST }} \
            --from-literal=REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --from-literal=RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
            --from-literal=RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }} \
            --from-literal=RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Clean up existing resources
        run: |
          echo "Cleaning up existing resources..."
          # deployment 삭제
          kubectl delete deployment,hpa -n ${{ env.NAMESPACE }} -l app=usage-query --ignore-not-found
          kubectl delete deployment,hpa -n ${{ env.NAMESPACE }} -l app=usage-management --ignore-not-found
          
          # deployment 완전히 종료될 때까지 대기
          echo "Waiting for pods to be cleaned up..."
          kubectl wait --for=delete deployment,hpa -l app=usage-query -n ${{ env.NAMESPACE }} --timeout=300s || true
          kubectl wait --for=delete deployment,hpa -l app=usage-management -n ${{ env.NAMESPACE }} --timeout=300s || true
          
          # 삭제 확인
          echo "Verifying cleanup completion..."
          REMAINING_DEPLOYMENTS=$(kubectl get deployment -n ${{ env.NAMESPACE }} -l 'app in (usage-query, usage-management)' 2>/dev/null)
          if [ -z "$REMAINING_DEPLOYMENTS" ]; then
          echo "All deployments successfully removed"
          else
          echo "Warning: Some deployments still exist:"
          echo "$REMAINING_DEPLOYMENTS"
          fi

      - name: Generate and apply Kubernetes manifests
        run: |
          # Set environment variables for manifest generation
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          export REGISTRY=${{ env.REGISTRY }}

          # Generate manifest using template and environment variables
          envsubst < deployment/manifest.yaml > generated-manifest.yaml

          # Print generated manifest for debugging
          echo "Generated Kubernetes manifest:"
          cat generated-manifest.yaml

          # Apply manifest
          kubectl apply -f generated-manifest.yaml

      - name: Wait for deployments to initialize
        run: |
          echo "Waiting for deployments to initialize..."
          sleep 30
          kubectl get all -n ${{ env.NAMESPACE }}

#      - name: Verify deployment
#        run: |
#          echo "Checking deployment status..."
#          kubectl get deployment -n ${{ env.NAMESPACE }}
#          kubectl rollout status deployment/usage-management -n ${{ env.NAMESPACE }} --timeout=300s
#          kubectl rollout status deployment/usage-query -n ${{ env.NAMESPACE }} --timeout=300s

      - name: Verify deployment
        run: |
          echo "Checking deployment status..."
          
          # Function to wait for deployment
          wait_for_deployment() {
            local deploy_name=$1
            local max_attempts=10
            local attempt=1
          
            while [ $attempt -le $max_attempts ]; do
              echo "Checking $deploy_name deployment (attempt $attempt/$max_attempts)..."
          
              if kubectl get deployment $deploy_name -n ${{ env.NAMESPACE }}; then
                kubectl rollout status deployment/$deploy_name -n ${{ env.NAMESPACE }} --timeout=60s
                return 0
              fi
          
              attempt=$((attempt + 1))
              sleep 10
            done
          
            echo "Error: $deploy_name deployment not found after $max_attempts attempts"
            return 1
          }
          
          wait_for_deployment usage-management
          wait_for_deployment usage-query

      - name: Print service endpoints
        run: |
          echo "Service endpoints:"
          kubectl get services -n ${{ env.NAMESPACE }}